### ISSUE TITLE
How are we handling the sending to 3 different lists?

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#10]
If it is premature to ask this, tell me to wait...

I was taking a sneak peak at everything on Staging-Padawan.  It's looking good.

I was curious how you plan to do the UI for sending the list to the 3 groups ('the media', staff, board).  

What I see now, is it looks to be

 - select-a-list
 - hit 'send campaign'
 - it tells you it did it, to which list, and when underneath button
 - then repeat

Is this right?

I am thinking having 3 buttons and 3 select-a-lists is a better UI.  They think of it as 3 different steps, and remember each list gets a slightly different MailChimp template (or 2 do).

Media:
 - select-a-list (with default)
 - hit send to media

Staff
 - select-a-list (with default)
 - hit send to staff

Board of Directors
 - select-a-list (with default)
 - hit send to board

But I am open to discuss.  Perhaps it could be argued this is it's own form of confusing and complicated.  And I may be commenting on stuff too soon in development...

**Comment by d4mation** [comment]
I personally think that having three separate forms like you mentioned may be too confusing, especially since it goes through a page refresh after hitting the "Send" button anyway.

What we may be able to do instead is set it up so that you can choose multiple lists at once so that it can loop through them and send them all in succession automatically. But in that use-case if you wanted to change any other parameters for any reason (Album URL, potentially From Name and Reply-To like we're talking about in #7) that wouldn't be possible. You would end up needing to send them one-at-a-time in order to do that.

**Comment by d4mation** [comment]
However, if we were to re-do some sections of the code to utilize AJAX we could remove the page refreshes and make having 3 different forms feel more natural. It would be a bit of an undertaking, but possible.

**Comment by d4mation** [comment]
This has been handled as part of #15.
