### ISSUE TITLE
'Grand Slam' UI/UX Concepts

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#15]
Hi guys.  Great work on the Press Release SOS.

I am trying to think big on the UI for this, all of this is open for discussion.  I'm thinking, in the end user's mind an interface something like this makes sense.

To them this is a routine part of there job, and it's a multi-step semi-linear process.  With a UI like this mockup below they have a fast, step-base process, that gives them all the options, but often they will just double-check and hit sent.

I realize this might change things programmatically some.  We may have to set a bunch of pre-sets on the 'Settings' pane, and then what you see on the actual Press Release CPT interface is pre-popluated.

Thoughts?  Am I crazy?

![press-release-sos-ui-concept1](https://cloud.githubusercontent.com/assets/9747248/18591128/5b766ab0-7bff-11e6-85a8-7da3110417b4.jpg)

**Comment by d4mation** [comment]
I only see two potential problems with this type of setup:

1. As mentioned in #10, currently hitting "Send Campaign" forces a Page Refresh. With some re-coding we could get this to utilize AJAX so the page does not refresh. 

According to [this](http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/#throttling), we can have up to 10 simultaneous connections at a time and each sending of a message uses 3 (in succession, so each one completes before the next starts). So with 4 forms, we _technically_ shouldn't ever hit the cap of 10 since at most only 4 connections should be made at a time, but it may be safest to disable all Sending Buttons until a Campaign Sends/Errors&mdash;Although that would take more time for the User as they would need to wait a few seconds between Sending Campaigns.

2. The logs could be redone so that they are per-form like this, but that could make this screen a bit messy. A separate column could be made for each one, but that could get pretty cramped adding 4 columns as opposed to the 1 currently being added.

![image](https://cloud.githubusercontent.com/assets/7770631/18591638/60d8a516-7c01-11e6-9e72-4e00362c1a4b.png)

**Comment by thisisjoewells** [comment]
Ok.  I feared it might cause mayhem.

## 1
One thing to bear in mind is that I suspect that 4th one will never be used.  I just thought it wise to build in an extra for rare edge cases.

Could AJAX be used just to 'block' the other send buttons from being clickable, while each one sends?

I'm ok if it they need to wait a bit between campaigns.  It's actually helpful in one sense.  The user will feel like they should have to wait while it does work.  It even feels good, like, "yes I told it to do all this automated stuff, now I will sit and watch it do my work for me, for a second".  

For example, I love watching the WP Migrate DB Pro interface go bar by bar for database table.  I usually don't read it, just watch it one the other side of my screen while I read email.  I like the visual confirmation, and while it works, I feel like and doing a form of very easy work.  Are you with me?

So as long as they have to wait, and the other buttons are temporarily disabled...this might be an easy way around making sure we don't max out on connections.


## 2

I agree that the Press-Release Listing screen would get messy with 4 columns.  I'm ok with just having a running record like you have now.  Is it possible to keep it as is, but just pick up the title that we give it like 'Media-Contacts' and 'Staff' and 'Board' and 'Other'?

**Comment by d4mation** [comment]
1. Yep, disabling the others should be possible. It is what I would rather do it for safety reasons, but I wasn't sure how quickly they needed to be able to zip through these. If having that feedback of "Oh, yes, it is doing its thing" helps, then that's a bonus!

2. Yeah, we can just spit them out as they are now buy give them little headers within the column. That could work.

**Comment by d4mation** [comment]
Quick update with this. I've got the new Form built&mdash;Now I just have to re-work the Campaign Sending process to be AJAX-friendly so we can eliminate those pesky Refreshes 👍 

This is constructed in such a way that if we decide to add/remove columns we can easily do so as well.

![image](https://cloud.githubusercontent.com/assets/7770631/18647315/63f71f64-7e83-11e6-9bc4-0134c6bddc11.png)

**Comment by d4mation** [comment]
I've pushed these changes to the `develop` branch if you want to see them on Staging.

However, clicking send will not work! In fact, I'm certain it will throw errors everywhere. The sending functionality needs to be reworked to match this new form.

**Comment by d4mation** [comment]
And now all the above bits are fixed! Whenever you get the chance, pull the changes from `develop` onto Staging and give it a whirl!

If that weird problem with it showing on the side is still there let me know. I believe that should be fixed as well.

**Comment by d4mation** [comment]
Closing. We've got a lot of other more specific Issues open now. Everything in this Issue seems to be covered.
