### ISSUE TITLE
Email/Column Defaults

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#18]
Can the 'columns' that represent email types here, have list and template defaults set?  Here is what they'd be.  To be manually overridden almost never.

If this was a group of settings on the global settings page that would be cool (vs. not being able to change them).

 - Column/Email - List - Template
 - Test/Other: DZS-Test-List - Media template
 - Staff: DZS-Staff-List - Other template
 - Board: DZS-Board-List - Other template
 - Media: DZS-Media - Media template

**Comment by d4mation** [comment]
This will be possible to add to the Settings Page, but they won't be visible/won't work unless an API key is entered (Since it needs to be able to grab the Lists/Templates via the API).

This should only ever be a problem once and only when it is first installed on Live, but I wanted to make that known.

**Comment by thisisjoewells** [comment]
This looks good, and I understand the one-time issue upon first installing on Jedi-Live.  We should be able to sort that out before end-users see it.
