### ISSUE TITLE
Media kit field description/caption

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#19]
Hi.
This one is easy.  Just some tweaks to the description/instruction/field caption.

Media Kit URL field description should add second sentence "No button will appear in emails if this is left blank.  Also add ‘Optional, ‘ to the front.  May as well swap DAM for Dropbox.  We'll never use DropBox for this, or it's highly unlikely.

So it would read:

Optional.  This can be a Google Drive URL, a DAM URL, etc.  No button will appear in emails if this is left blank.

**Comment by d4mation** [comment]
Unfortunately, due to how MailChimp's Templating Language works, that second bit actually isn't possible. They oddly don't have a way to say "If this data is sent in the request, hide/show this content block"&mdash;They have it for other things, but not for the API. It is really strange.

Right now if nothing is added into that field a blank, non-functioning "button" is added to the e-mail.

We may be able to get around this with some different CSS, but as it is right now the `<table>` element that holds the Button is what holds the background color as that's how MailChimp's Template Builder originally generated it. I'm guessing this may be some way to make the styling more compatible across e-mail clients (or at the very least I hope so), as it seems like a very odd way to handle it to me.

The `<div>` with the `mc:edit` attribute is where the button's HTML is actually added to the template.

![image](https://cloud.githubusercontent.com/assets/7770631/18763491/a1280fba-80db-11e6-9ac2-c4f659ad30f7.png)

**Comment by d4mation** [comment]
^ This is why there are two nearly identical templates for Media and "Other" as there was no good way to simply hide the button if the field were left empty. The Other Template is the same as Media but with the PDF Button removed.

**Comment by thisisjoewells** [comment]
Ah I see.  It's a bit like the Italics issue on #26 - baked-in to MailChimp can't change.

I wonder if we should make this modification to our whole plan then.

Let's just have 3 templates?

Template 1 - Word Doc/PDF Button only
Template 2 - Word Doc/PDF and Media Kit Buttons
Template 3 - No Buttons

I'll set up the Staff and Board to go with Template 3.

I'll set up the Media to default to Template 1.  Then if and when we have a Media Kit, they will select template 2.  That's good and straightforward?

**Comment by d4mation** [comment]
I just created the 3rd template with no Buttons and refreshed the Transients on Staging. It would need to be set as a Default wherever needed, but it is an option to be chosen now 👍 

(I also renamed them all to say "Media Release" rather than "Press Release" as per #21)

**Comment by thisisjoewells** [comment]
This is good.

I was just thinking it might be even easier to use and more fool-proof if we just call the templates by exactly what they are.  No ' Media Release -' even needed.

I found myself a bit confused as to which one was which.  But there would be no confusing it this way:

2 Buttons - Word/PDF and Media Kit
1 Button - Word/PDF Only
No Buttons

Since they are otherwise the same, right?  Thoughts?

**Comment by d4mation** [comment]
That's a-okay with me. I'll rename them real quick.

**Comment by d4mation** [comment]
Just renamed them 👍

**Comment by thisisjoewells** [comment]
Looks good.
Where is this controlled, by the way, I thought it'd be in the MailChimp template, but I don't see it.  At least not in the editable code?  Just curious if it's easy to change ourselves if ever needed.

Let's put this into Master and push to Jedi-Live!?

I see no danger in doing this.  It's Monday.  I'll do a test right away to make sure all is well.  There are nothing but DZS and RBM test contacts on MailChimp lists right now...

**Comment by d4mation** [comment]
The settings for the Template Names are on MailChimp Under `Templates->Edit Template->Rename->Save and Exit` (The `DZS-API-` prefix is so that we only load our custom, API-ready, templates)

I'll get the code up onto Jedi-Live here in just a moment 👍 

![image](https://cloud.githubusercontent.com/assets/7770631/19242755/92155e0a-8ee2-11e6-9d54-ae3d9832d85c.png)

**Comment by d4mation** [comment]
Code is now on Jedi-Live! The API key will need to be added into the Settings Page to get started, but from there things should operate just as they do on Staging.

**Comment by thisisjoewells** [comment]
Cool.  Thanks for doing that whilst uber-busy.  We will begin official QA.
