### ISSUE TITLE
Consistent control of Pre-Header - Possible?

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#34]
Hi @brashrebel - I'm not sure of the billing status on PR-SOS.  Every time I go to train (so we can "launch") Patricia/Jennie, three times now, they notice things and request changes, despite my attempts to avoid this with email previews, meetings, and whatnot.  I'm sure you agree we want them to like this thing we are building them, so we need to make these legit improvements they point out.  Frustrating workflow though.

This may be a small change, I need help, I don't think I can do this one.

@d4mation, basically they shredded the gray pre-header box today.  They complained that it effectively shows the subject line 3 times in an email, and this looks bad, especially on mobile.  Valid point.   They said for Press Releases no one will ever need to view in a browser, which is arguable.

I wish, of course, pointed this out 4 months and any time in between, when they might have mentioned this.  They have been reviewing previews.

So I just removed this whole darker gray pre-header box/area from the no-buttons template.  But.  PROBLEM.  Things get inconsistent on the little preview that every email client uses a bit differently.

Can we consistently have the preview-lines of emails display the first few words of the press release (not title/subject line, and not 'For Immediate Release...' which are differnt API items,  I think).  We could put an API call into the template for this?

## Example - Outlook 2016 Mac Client - Acceptable
Shows first text, though not ideal that it's "For Immediate release...."

![outlook-pre-header1](https://cloud.githubusercontent.com/assets/9747248/20275916/43f14fa8-aa68-11e6-963e-ec6edc2c808a.png)

## Example - iPhone - BAD
Shows image link in text "https://gallery.mailchimp..."

![iphone-pre-header1](https://cloud.githubusercontent.com/assets/9747248/20275982/76f58806-aa68-11e6-9e3f-8688574c3cea.png)

## Example - Gmail - Acceptable
Shows first text, though not ideal that it's "For Immediate release...."

![gmail-pre-header1](https://cloud.githubusercontent.com/assets/9747248/20276070/c10089b4-aa68-11e6-8bea-4b1c87e0ea3e.png)

## So, can we either?:

- Specify an API call somehow that pulls the actual Press Release Text, not sure how to 'hide' it in the main template body?
- Or - at least fix it so iPhone doesn't show link text, not sure best way?

**Comment by d4mation** [comment]
This is an interesting problem indeed. If you look at the source [here](https://github.com/TheDetroitZoo/pr-mailchimp-integration/blob/fd1f15215cb8c3c2c3648c264c975de44c03fca1/core/admin/class-dzs-mailchimp-admin.php#L451-L483) you'll see how the Campaign Content is getting passed to MailChimp with the [API documentation here](http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/content/#edit-put_campaigns_campaign_id_content).

We're passing `plain_text` which is basically whatever is placed within the Content Editor without any HTML along with straight URLs to what would normally be buttons. My assumption would be that in a quick preview (Like what each Email Client above shows before you actually open them) it would use the `plain_text` value rather than trying to load the entire Template but that doesn't appear to be the case in every situation.

I'm not sure how MailChimp's Campaigns determine whether to show the plain text variant of the Campaign or the full-blown HTML variant, but my guess it that it has to do with some type of "User Agent" being reported by the Client. When the Client is showing that quick preview it must be saying "Hey, I can render HTML. Throw it at me." and attempts to render the HTML even when it shouldn't. Considering the Image in particular is part of the Template that's what I think is happening (As it wouldn't make sense to use a Template when you're supposedly serving plain text). That's the only explanation I can come up with for the different Clients to show the exact same email different ways.

Unfortunately, this means that it could be considered a Template problem. That means that either:

1. The image needs to be moved so it isn't the first thing in the email.
2. Something needs to be placed above the image so that _it_ is the first thing in the email (Like the gray bar that was unfortunately removed).

I agree that having the Subject Line up there probably wasn't a good idea given how just about any Email Client would view it, but I'm thinking that something else up there may be a good idea. Even if it is something static like a quick slogan or motto or something.

Phew, big wall of text. Let me know if something doesn't make sense!

**Comment by brashrebel** [comment]
Mail Chimp emails already default to having a teaser text section at the top specifically to address this problem. When you're creating these campaigns in Mail Chimp you just put something in that text box. So we just need something like that in the template I guess.

You could even dynamically take the first sentence from the content, put it up top and then...hide it? Not sure if the email clients would still show it or not. But it would prevent the necessity of creating another field to fill when publishing Press Releases.

**Comment by thisisjoewells** [comment]
Hi.  Thanks @d4mation  - I am totally tracking with the entire wall of text.  All makes sense.

I was thinking almost the same thing, but had not gone 'as deep' as the user-agent plain-text/html as probable source beneath the symptom.  It's a good guess, so good it must be called a theory :)

I agree that if you are right it's a template problem.  Even more precise, a phantom template problem that may or may not occur based on an unpredictable mix of factors based on device and email client.  Because, yeah, what Gmail and Outlook do is good enough...but iPhone with built-in mail client is bad.

Yes, the subject line being there is no good.  Also no good is for the preview text to say 'view this email in a browser'.  This is a so-5-years ago email marketing faux-paux that most people have fixed.

There's got to be a way to either, as you said, put a little quick slogan....or...something dynamic like....WAIT.....a comment from Kyle suggesting, basically, what I was going to say just popped up.  Yes.  Like that ( @brashrebel 's post right above this).

The ideal, but it may be impossible, would be to put the first sentence in there with some fancy tom-foolery.  But then hide it.  Sounds crazy.

**Comment by thisisjoewells** [comment]
Ok.  Thanks for you work on this so far guys...

I'm thinking over all the possibilities and challenges from what you mentioned @d4mation.  I don't really want to have a new field for them.  Hmm...  Thinking.

For a first version of a fix/consistent pre-header I am leaning towards a slogan of some sort...so we can have this ready soon/fast/this week.

Because - we are going to send the first Press Release from SOS on Thursday around 10 AM.

**Comment by thisisjoewells** [comment]
Note: see #37 -
We accidently forgot to include the CPT field 'sub-heading' in the emails.  In #37 we are talking about adding it in, and, using as the preview-text/pre-header.  This is nice.  Fixing two things at once.

In cases where there is no sub-heading written, in global settings we are thinking we'll make a 'default preview text'

**Comment by d4mation** [comment]
Closing in favor of #37.
