### ISSUE TITLE
Can the 'Global from' or 'Organization Name' not be used?

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/pr-mailchimp-integration#36]
This get's confusing a bit.  I know we've talked about this before.

The Organization name should not be used in the 'From' of the email.  It was set to Detroit Zoological Society, but emails will always need to come from the media contact Patricia or Jennie in this case.

I can foresee them getting confused.  On the 4-column interface there is the place where we can set the 'Contact name'.  Changing that should change both the 'From name' in the email and the 'contact' in the body of the email.  Otherwise they will get confused.  They will change the name in 'contact' to Jennie when Patricia is out of town but then be mad that it still came from 'Patricia' in email subject 'from'.  Are you following me?

**Comment by brashrebel** [comment]
Should it just be set to use the author of the Press Release? As in the logged in user who's publishing it?

**Comment by d4mation** [comment]
I see, so the From Name will ALWAYS be Contact Name now? I suppose Organization Name could be scrapped if that's the case. Before it was meant to be a way for more flexibility so that E-Mails could be sent as from "Detroit Zoological Society" while still having the Contact Name within the Template set to something else for example. I guess if people are on these mailing lists they could be assuming to get e-mails from Patricia or Jennie (As these are Press Releases, not run-of-the-mill Blast Emails).

Assuming I'm understanding you correctly that is.

**Comment by thisisjoewells** [comment]
@brashrebel - good question.  It would be clean and easy to do that, but it won't work since there is a good chance a PR intern might draft or just do the timed send-out of the emails on behalf of the PR-Face-Woman who is credited as author and listed as contact.

@d4mation - Yes.  This would be ok, if it doesn't break something.  Just lose Organization Name.  I appreciate the work and thought we'd need the flexibility.  But now I think it will just risk confusing them.  Press Release emails will always be 'personal' and come from a PR contact, is what they affirmed today.

So yes, you are understanding correctly, and I may not have been understanding end users, or they didn't communicate it the best.  

- The users on the mailing list are used to and expect to be getting it from DZS as a given
- Those users expect it to be a personal email from the contact that they can contact by hitting reply, and so on
- PR/Comm team doesn't want this to come from the Society (DZS) as an organization, like a marketing eBlast, but rather a personal-professional email from a direct contact

**Comment by d4mation** [comment]
In a similar vein, is there still any separation between Reply-To: and the Contact Email?

Having a different Reply-To: Email was again for flexibility, but if the assumption is that hitting "Reply" will always immediately reply to the Contact rather than another email address that could be scrapped as well.

**Comment by thisisjoewells** [comment]
Yes.  You are right, if we get rid of one, may as well not have the other.

As long as the are focused on emails being 'peronal-professional' from one person.  They should only have to change or override the Contact-name and Contact-email and that will change the from name and email.

Can we do this by tomorrow end of day?  We are going to send the first Press Release from SOS on Thursday around 10 AM.

**Comment by d4mation** [comment]
I just finished this up on the `issue/36/no-more-organization-name` branch. When you get the chance, could you test that out to ensure that it is working well?
